services:
  - type: web
    name: assistente-chat-pdf
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: 1ULRe_-U-3bZ6vtP-QRJdjUd27AEdFkBx
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
